### ISSUE TITLE
No check for max batch payload size.

### ISSUE THREAD

**Issue by kritollm** [Azure/azure-storage-node#144]
What happens if the 100 enteties in a batch result in a payload of more than 4mb? Does the sdk split the batch in smaler batches or does it just fail?

**Comment by kritollm** [comment]
I looks like there is no validation on the payload size. I need to implement that because I'm going to write a table backup/restore utility where the entity size is unknown. And I think it's not a good option to calculate the size because then we need to serialize the entity twice.

Here is a very simple solution:
`BatchResult.prototype.serialize = function () {
    var body = '--' + this.batchBoundary + '\n';

    var sizeLimit = 2 * 1024 * 1024; // 2 = 4MB of text.

    if (this.operations.length === 1 && this.operations[0].type === TableConstants.Operations.RETRIEVE) {
        body += HeaderConstants.CONTENT_TYPE + ': application/http\n';
        body += HeaderConstants.CONTENT_TRANSFER_ENCODING + ': binary\n\n';
        body += this._serializeOperation(this.operations[0]);
    } else {
        body += HeaderConstants.CONTENT_TYPE + ': multipart/mixed;charset="utf-8";boundary=' + this.changesetBoundary + '\n\n';

        for (var i = 0; i < this.operations.length; i++) {
            body += '--' + this.changesetBoundary + '\n';
            body += HeaderConstants.CONTENT_TYPE + ': application/http\n';
            body += HeaderConstants.CONTENT_TRANSFER_ENCODING + ': binary\n\n';
            body += this._serializeOperation(this.operations[i], i) + '\n';
            if(body.length >= sizeLimit){
                // Throw error, or store the index so user can split up his batch
                break;
            }
        }
        body += '--' + this.changesetBoundary + '--\n';
    }
    body += '--' + this.batchBoundary + '--';
    return body;
};`

**Comment by hasonmsft** [comment]
@kritollm , thanks for raising this issue. We'll triage this and try to address it in the upcoming release.

**Comment by kritollm** [comment]
Thanks. It will not happen often, so just returning index of error will probably be good enough and very easy to implement.

**Comment by hasonmsft** [comment]
@kritollm , after the internal triage, we decide to keep it as it is now as the batch payload size threshold may be changed in the future. 

To workaround your issue, you can: 

1. Keep it as it is now - it'll have unnecessary service round-trip if the payload size exceed 4MB. But you can still get the error as service will reject the request finally. 
2. Check the batch count from the experience in your project instead of leveraging the built-in batch count validation (by default 100). E.g. you can check if the batch count exceed the value you defined - e.g. 50 to make sure it won't exceed the 40MB payload size threshold. 

Please let me know how do you think about this.

**Comment by kritollm** [comment]
It's fine for my needs. The reason I brought it up was that I was thinking of making an app for easy security copying (and restoring)  of tables to blob or file that just worked, but It's to time consuming so I will only write a node script for my own use.
