### ISSUE TITLE
InvalidXmlDocument

### ISSUE THREAD

**Issue by dwhieb** [Azure/azure-storage-node#146]
I'm having trouble understanding the reason for this error when using the Node SDK:

```
{ [Error: XML specified is not syntactically valid.
RequestId:3fdd03b3-0001-0080-3c1d-96f77e000000
Time:2016-04-14T07:18:01.6212820Z]
  code: 'InvalidXmlDocument',
  linenumber: '0',
  lineposition: '0',
  reason: '',
  statusCode: 400,
  requestId: '3fdd03b3-0001-0080-3c1d-96f77e000000' }
```

Here is my code in its entirety:
```
const Storage = require('azure-storage');
const storage = Storage.createBlobService();

storage.getServiceProperties((err, res) => {

  res.Cors.CorsRule = [
    {
      AllowedOrigins: ['*'],
      AllowedMethods: ['GET']
    }
  ];

  storage.setServiceProperties(res, (err, res) => {
    console.log(err || res);
  });
  
});
```

I followed the documentation [here](http://azure.github.io/azure-storage-node/#toc9), but I can't tell whether this is an error on my end, or a problem with the SDK. Thanks for any help!

**Update:** I found [this issue](https://github.com/Azure/azure-storage-node/issues/23) but unfortunately still wasn't able to resolve the problem.

**Comment by hasonmsft** [comment]
@dwhieb , may I know what's the SDK version are you using?

**Comment by dwhieb** [comment]
Sure - I'm using 0.9.0. But I actually was just now able to resolve my issue by changing my code to the following:

```
const Storage = require('azure-storage');
const storage = Storage.createBlobService();

storage.getServiceProperties((err, res) => {

  const Storage = require('azure-storage');
  const storage = Storage.createBlobService();

  storage.getServiceProperties((err, res) => {

    res.Cors.CorsRule = [
      {
        AllowedOrigins: ['*'],
        AllowedMethods: ['GET'],
        AllowedHeaders: [],  <= added this
        ExposedHeaders: [],  <= and this
        MaxAgeInSeconds: 500  <= and this
      }
    ];

    storage.setServiceProperties(res, (err, res) => {
      console.log(err || res);
    });

  });

});
```

The response I got was this:
```
{ isSuccessful: true,
  statusCode: 202,
  body: '',
  headers:
   { 'transfer-encoding': 'chunked',
     server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
     'x-ms-request-id': '1ec6f7ce-0001-00db-3f20-96f002000000',
     'x-ms-version': '2015-04-05',
     date: 'Thu, 14 Apr 2016 07:37:18 GMT',
     connection: 'close' },
  md5: undefined }
```

Even better, this did in fact enable CORS requests. I was able to retrieve blobs via a cross-origin request after this setting had been changed.

**Comment by hasonmsft** [comment]
@dwhieb , great to hear you resolved your issue. Please let us know in case of any other issues.

**Comment by yaxia** [comment]
@dwhieb, good to know it is resolved. To help you better understand the root cause, you might want to refer to this [page](https://msdn.microsoft.com/en-us/library/azure/hh452235.aspx). All the CORS elements are required for a CORS rule.

AllowedOrigins 
**Required** if CorsRule element is present. A comma-separated list of origin domains that will be allowed via CORS, or "*" to allow all domains. Limited to 64 origin domains. Each allowed origin can have up to 256 characters.
 
ExposedHeaders 
**Required** if CorsRule element is present. A comma-separated list of response headers to expose to CORS clients. Limited to 64 defined headers and two prefixed headers. Each header can be up to 256 characters. 

MaxAgeInSeconds 
**Required** if CorsRule element is present. The number of seconds that the client/browser should cache a preflight response. 
 
AllowedHeaders 
**Required** if CorsRule element exists. A comma-separated list of headers allowed to be part of the cross-origin request. Limited to 64 defined headers and 2 prefixed headers. Each header can be up to 256 characters.
 
AllowedMethods 
**Required** if CorsRule element exists. A comma-separated list of HTTP methods that are allowed to be executed by the origin. For Azure Storage, permitted methods are DELETE, GET, HEAD, MERGE, POST, OPTIONS or PUT.

**Comment by dwhieb** [comment]
Awesome - thanks! I forget that I can look at the actual API docs in addition to the SDK docs...
