### ISSUE TITLE
SAS URLs don't work

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-storage-node#175]
I used the following code from the documentation:
```js
        var sasToken = this.blobService.generateSharedAccessSignature(USER_MODELS, id, {
            AccessPolicy: { Expiry: azure.date.minutesFromNow(60) }
        })
        var sasUrl = this.blobService.getUrl(USER_MODELS, id, sasToken, true)
```

However, the url is such that I get an error message when I try to download the resource. The error is:

**sp is mandatory. Cannot be empty**

Is this a bug or did I forget something?

**Comment by asorrin-msft** [comment]
This looks like a doc bug, could you share where this was documented, so that we can correct it?
You need to specify what kind of permissions you're granting (read, write, read + write + delete, etc).  There's a correct sample here:

https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-blob-storage/#work-with-shared-access-signatures

**Comment by letmaik** [comment]
It's in the getUrl doc string: http://azure.github.io/azure-storage-node/blobservice.js.html#sunlight-1-line-2230

**Comment by hasonmsft** [comment]
@letmaik , thanks for raising this issue. Will update the documentation.

**Comment by hasonmsft** [comment]
@letmaik , the document is updated.

**Comment by letmaik** [comment]
Cool, thanks!
