### ISSUE TITLE
Multer Stream Upload to blob

### ISSUE THREAD

**Issue by tomalex0** [Azure/azure-storage-node#201]
Anybody tried uploading image to blob  using multer as stream, below code works for me, would like to know if there is better alternative to convert buffer to stream.?

```
var multer  = require('multer');
var storage = multer.memoryStorage();
var upload = multer({ storage: storage });
var azureSorage = require('azure-storage');
var blobSvc = azureSorage.createBlobService();
var streamifier = require('streamifier');

router.post('/api/fileupload', upload.single('single_fileup'),function(req, res, next){
       console.log(req.file,'----files--',req.body);


        var stream = streamifier.createReadStream(req.file.buffer);
        console.log(stream)

        blobSvc.createBlockBlobFromStream(
            'images',
            req.file.originalname,
            stream,
            req.file.size,
            function(error, result, response){
                console.log(error,result,response);
                if(error){
                    console.log("Couldn't upload stream");
                    console.error(error);
                } else {
                    console.log('Stream uploaded successfully');
                    req.model.data = response;
                    next();
                }
            });

    }, renderJSON);
```

**Comment by hasonmsft** [comment]
@tomalex0 , streamifier is good. :) And did you find any better solution to share here?

**Comment by jimmynewso** [comment]
I'm kind of a novice, but I've been working on something similar and I had an idea.

So, the way your doing it, multer uploads the whole thing into memory (buffer) and then you pass it as a stream to azure right? I'm not sure you can do it with multer, but I'm pretty sure it's possible to just pipe the original upload stream straight to azure, and this might be a tiny bit faster. You could probably do it with busboy, since it lets you grab the file upload stream.

I don't know about the practical benefits though, might be pretty negligible. idk if this helps, just trying to contribute.

**Comment by atsgeiger** [comment]
I am curious if ghost was able to figure this out - I might need to load some files that are somewhat large (>50mb) and it'd be nice not to load that into memory or cache on disk but stream it as soon as I get it, part by part.
