### ISSUE TITLE
Data Table getEntities() returns 0 entries, but has a continuationToken

### ISSUE THREAD

**Issue by trevorfrese** [Azure/azure-storage-node#244]
I'm encountering a very strange error. I'm running a query to get all of the entities in my table with a certain partition key and row key combination using this function:
`tableSvc.queryEntities(tableName, query, null, function(error, result){})`

But I get this result 

```
{ entries: [],
  continuationToken: 
   { nextPartitionKey: '<PartitionKey>',
     nextRowKey: '<someRowKey>',
     targetLocation: 0 } }
```
Why is it returning 0 for entries, but there is a continuationToken? Also there are definitely thousands of entities in the table matching that query, so it should not be returning 0. Additionally, I run the same exact query in Azure Storage Explorer and it returns all of the entities.

**Comment by mirobers** [comment]
The Storage Service returns a continuation token for multiple reasons, including limiting the max number of elements returned, limiting the time of the query, and due to backend partitioning. If you encounter a continuation token with no entities returned, it means that the service didn't find any entities matching the query before returning a continuation due to the reasons above.

The service did make progress on the query, so you should follow the continuation token(s) to get the full list of results. This is what Azure Storage Explorer does to get the results.

If you are seeing a lot of requests return no results then it could be that your query is not optimal and is resulting in a full table scan to scan over many entities that don't match your filter. Including tighter bounds on the partition key and row key in your query could help improve the performance in this case.

**Comment by trevorfrese** [comment]
Okay, so if I just leave it running it, it will eventually find the entities? 

Unfortunately in this case it is not possible to tighten up the Partition Key and Row Key as they need to iterate over a large search space. I'm migrating data from one Azure Table to Another, but only the data that matches this specific Partition Key and Row Key combination.

**Comment by mirobers** [comment]
Yes, it will find all entities. It should not take longer than Storage Explorer, which uses the same method internally.
