### ISSUE TITLE
Can't set blob property or metadata value to Unicode characters

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#252]
Trying to use blobService.setBlobProperties to set Unicode values into a blob property or metadata, e.g. "五星红旗".

I end up with this error: The header content contains invalid characters

Is this supported by Azure?  Should the library be automatically encoding/unencoding?

Thx.

**Comment by yaxia** [comment]
The metadata is transferred in the HTTP headers. Since [RFC2822](https://tools.ietf.org/html/rfc2822#section-2.2), message header names and values should be ASCII characters; values that contain non-ASCII data should be encoded. 
From the library's point of view, it is easy to encode but it cannot determine whether it should decode when fetches those values without additional information. So I'd suggest the application to handle the encoding/decoding.

**Comment by StephenWeatherford** [comment]
Okay, thanks.
