### ISSUE TITLE
Large file uploads fail in low bandwidth situations (client library issue)

### ISSUE THREAD

**Issue by dehildum** [Azure/azure-storage-node#297]
Attempting to upload a 2GB file as a block blob fails when the upload speed is less than 5600Kb/s. 

On Safari, eventually I start receiving ETIMEOUT issues which were probably bogus reports given the timing of error. Safari continued to attempt to upload blocks to the end of the upload, thus the error callback did not fire when the error started occurring (I never waited for the callback to fire).

IE reports an uncaught exception (on a new of a Javascript object, if the information was correct) and halts the JS.

Chrome fails as well but I did not have logging enabled at that point.

The code was effectively the blob sample, though I used storage keys instead of SAS tokens.

Safari and IE failed about 70% of the way in the upload reasonably consistently, Chrome failed at 12% but I do not know if that is repeatable.

Separately, I may have seen the same problem in a node.js implementation. Not entirely certain.

**Comment by XiaoningLiu** [comment]
Hi @dehildum, Thanks for opening the issue here from Slack. BTW, could you please provide the version numbers of your OS and IE/Chrome/Safari?

**Comment by XiaoningLiu** [comment]
We confirm this issue - **The upload methods will keep reading data from stream even after a failure**. The issue is in Azure Storage Node.js SDK implementation. When a failure happens, such as ETIMEOUT error, if there is no retry-policy set for blobService, the uploading will be stopped, but it will keep reading data from the file stream until the stream is end. Will fix it in following releases.

BTW, in a low-bandwidth environment, better to setup a retry-policy for a blobService object. Please refer to here:

https://azure.github.io/azure-storage-node/RetryPolicyFilter.html

**Comment by seguler** [comment]
So, setting up a retry policy is the workaround ?

**Comment by XiaoningLiu** [comment]
The retry policy cannot promise 100% successful uploading, but it can reduce the possibility of failures in a low-bandwidth environment. If a request keeps failing after retry times set in the retry policy, the upload will eventually fail.

Currently **when the upload failed, the library will keep reading data from stream**. That is the issue we need to fix, when the upload failed due to error, the library should stop reading stream and return error immediately.

**Comment by XiaoningLiu** [comment]
@dehildum @seguler

Here are candidate workarounds for uploading GB-level blobs in a low-bandwidth network environment:

###	Add retry-policy for blobService [Highly recommend]
```
var retryPolicy = new AzureStorage.ExponentialRetryPolicyFilter();
var blobService = AzureStorage.createBlobServiceWithSas(…).withFilter(retryPolicy);
```
###	Reduce uploading concurrency
The default uploading concurrency is 4, we can reduce the concurrency by set the options parameter of blobService.createBlockBlobFromStream.
```
var speedSummary = blobService.createBlockBlobFromStream('mycontainer', file.name, fileStream, file.size, {parallelOperationThreadCount: 1}, function(error, result, response) {…}); // Set concurrency level to 1 (no concurrency)
```
### Reduce default uploading trunk size
A huge blob will be split into 4MB trunks for uploading by default. If the network is too slow that make a 4MB uploading timeout. We can try to set a smaller trunk size. (Not recommend to set a very small size which will reduce the performance)
```
var speedSummary = blobService.createBlockBlobFromStream('mycontainer', file.name, fileStream, file.size, { blockSize: 1024 * 1024}, function(error, result, response) {…}); // Set 1MB trunk size
```

**Comment by dehildum** [comment]
Gentlemen, thank you for looking into this. For various reasons, I will not be able to do further testing at this time, but will keep you retry recommendation in mind should I need to do this again.
