### ISSUE TITLE
Client library sometimes creates bad authentication string

### ISSUE THREAD

**Issue by dehildum** [Azure/azure-storage-node#298]
Running code similar to blob sample, when attempting to upload blob I occasionally get Authorization problems. The storage service gives me a 403 bad authorization and complains the authorization string is incorrect. Sometimes retrying immediately solves the issue, other times I have to retry multiple times (I just hit the upload button on my form again to trigger the creation of a new blob service and retry the upload).

There appears to be an intermittent fault in the authentication string generation routines.

Current Safari browser.

**Comment by XiaoningLiu** [comment]
Hi @dehildum , can you describe the versions of your OS and Safari browser?

**Comment by XiaoningLiu** [comment]
@dehildum The 403 bad authorization is likely to be caused by the timeout of x-ms-date header. 

Can you share the log along with the **x-ms-client-request-id** for the 403 error? Then we can get the error details from the Azure Storage server side.

Here are the authentication rules for the Azure Storage requests.

https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/authentication-for-the-azure-storage-services#a-namesubheading1a-specifying-the-date-header

`The storage services ensure that a request is no older than 15 minutes by the time it reaches the service. This guards against certain security attacks, including replay attacks. When this check fails, the server returns response code 403 (Forbidden).`

**Comment by hasonmsft** [comment]
@dehildum , please also share the account name. :) HTTP request/response trace is also very helpful for troubleshooting.

**Comment by dehildum** [comment]
Gentlemen, unfortunately I cannot provide further information at this time. This came up in the last week of a contract, and I no longer have access to the codebase to perform testing.
