### ISSUE TITLE
generateSharedAccessSignature Needs a Callback

### ISSUE THREAD

**Issue by chadcampbell** [Azure/azure-storage-node#315]
Hello,

I believe that the `generateSharedAccessSignature` function needs a callback function. This callback would be fired once the shared access signature is active. The reason I believe this is because, at this time, I'm experiencing the following.

I successfully generate a shared access signature for an image I have in Azure Storage. I then try to load that image via the image URL with the shared access signature. I've noticed that it only works sometimes though. When it fails, I receive the following error: 

```
Invalid image URL or error downloading from target server. Remote server error returned: "Response status code does not indicate success: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.).
```

As a workaround, I've been able to overcome this issue by wrapping my image loading code in a `setTimeout` and waiting 10 seconds. This isn't the most robust approach. A callback function that's fired when the shared access signature is active would be more robust.

**Comment by XiaoningLiu** [comment]
Hi @chadcampbell 

`generateSharedAccessSignature()` function executes a offline sign algorithm to generated a SAS token based on an account key. Callback is not very necessary in that case, because of no server request is performed.

Can you check with the **startTime** you used to generate the SAS token? Difference between your localtime and the server time may cause the latency issue. One more tip, **startTime** can be set a time ahead the time you called the `generateSharedAccessSignature()`.

**Comment by chadcampbell** [comment]
Thank you for the information. I revised the `startTime`  used to generate the SAS token and everything seems to be working fine now. I was using:

```
let startDate = new Date();
```

As mentioned in the documentation you shared, that was earlier than 15 minutes in the past. That's why it was behaving inconsistently.

Thank you for your help!
