### ISSUE TITLE
Unrecognized Edm.Int32 literal

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-storage-node#316]
Just upgraded to latest version on npm, the client (tables) is now throwing the following error:

`{ code: 400,
  message: 'Unrecognized \'Edm.Int32\' literal \'1498179600055\' \nRequestId:95362c0f-0002-010b-23bc-eb966e000000\nTime:2017-06-23T01:00:01.0846519Z',
  status: 'InvalidInput' }`

Has Edm.Int32 been replaced with something else?

**Comment by 1N50MN14** [comment]
closing

**Comment by bhosalemahesh899** [comment]
Hi,
Is this issue resolved?
I am getting the same issue, Can you please assist me on this
`{
  "Message": "The query specified in the URI is not valid. Unrecognized 'Edm.Int32' literal '12222455555555155555' at '21' in 'AutotaskAccountId eq 12222455555555155555'.",
  "ExceptionMessage": "Unrecognized 'Edm.Int32' literal '12222455555555155555' at '21' in 'AutotaskAccountId eq 12222455555555155555'.",
  "ExceptionType": "Microsoft.Data.OData.ODataException",
  "StackTrace": "   at Microsoft.Data.OData.Query.UriQueryExpressionParser.ParseTypedLiteral(ExpressionLexer lexer, ........"
}`

**Comment by sampaioletti** [comment]
Super disappointing that nobody answered this, fought this annoying issue for a long time, for me the issue was related to a type mismatch. 

I was storing a javascript Date.now() into a Emd.Double in my table. But when querying it defaults to a Int32 when you pass a number for some reason. 

Long story short, I started storing my Date.now() into a bigint in js and then storing it into a Edm.Int64 in my table and was able to query it using 
```js
TableQuery.int64Filter("exp","le",[bigint])
```
while YMMV try looking at your types you may have a mismatch

**Comment by Tiger519** [comment]
This is still an issue... I couldn't find any way to use a double in the query, even replacing the variable with `?double?` as I saw in another example. I too was storing Date.now() and needing to do a query later. I didn't need millisecond precision so I just converted into seconds via `Math.floor(Date.now()/1000)` on both table population and the query. Didn't try the above method but if seconds precision is enough this was super easy to implement.
