### ISSUE TITLE
The contentDisposition does not work with the createWriteStreamToBlockBlob method option.

### ISSUE THREAD

**Issue by captyoungkyu** [Azure/azure-storage-node#339]
```
file.pipe(m).pipe(blobStorage.createWriteStreamToBlockBlob(container, `${random}/${filename}`, {
        contentSettings: { contentType: mimetype, contentDisposition: `attachment; filename="${encodeURIComponent(filename)}"` },
      }, (error) => {
```

I wrote this. But it does not work. I wrote it exactly as written in the document. 

It seems a bug. I would appreciate it if azure team fix it.

**Comment by capt-youngkyu** [comment]
I found the reason.
I set up a blob access policy. However, why is contentDisposition working only when used with sas? 
Is this intended?

**Comment by jiacfan** [comment]
Hi, @capt-youngkyu :

Thanks for giving feedback, for the questions you posted:

1. Why `createWriteStreamToBlockBlob` doesn't return Content-Disposition header?
`createWriteStreamToBlockBlob` API uses 'put blob' REST API [https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob](url) to create and update contents of block blob. As the REST API reference, if contentDisposition is provided, the blob's Content-Disposition header would be be saved with blob, while the response for 'put blob' wouldn't contain Content-Disposition header and that's why directly using createWriteStreamToBlockBlob would not get response with Content-Disposition header. And if want to get it work:

> The response from the Get Blob and Get Blob Properties operations includes the content-disposition header.
--

2. Why SAS works? 
Does the SAS token being used contains 'rscd' query parameter? As [https://docs.microsoft.com/en-us/rest/api/storageservices/Service-SAS-Examples?redirectedfrom=MSDN](url) mentioned:

> Version 2013-08-15 introduces new query parameters that enable the client issuing the request to override response headers for this shared access signature only. 
--

So if your SAS token contains 'rscd' query parameter, the response header would contains Content-Disposition.

Best Regards,
Jiachen
