### ISSUE TITLE
getBlobMetadata & getBlobProperties return 'NotFound' whether blob or bucket does not exist

### ISSUE THREAD

**Issue by electrachong** [Azure/azure-storage-node#356]
Hello,

I have another inquiry that came up while I was working with the node client library (v 2.4.0).

I am not sure it is a bug, but it would be helpful if getBlobMetadata/getBlobProperties returned different error codes when getting the blob from a non-existing bucket versus getting a non-existing blob from an existing bucket.

Based on the [Blob Service Error Codes](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes), I expected `BlobNotFound` or `ContainerNotFound` to be returned in the respective cases (which seems true of other blob-level apis when using the node client library), but instead I got `NotFound` in both cases (which is not listed in the error codes except as a http status code).

Is it something that can be addressed?

Thank you!

**Comment by XiaoningLiu** [comment]
Hi @electrachong 

Thanks for pointing this out! There are differences on returned Status Code between getBlobMetadata/getBlobProperties with other blob-level apis. The differences is due to the different Azure Storage Service REST API returned messages.

For other blob level APIs such as `getBlobToText`, the REST API will return a error body, including the storage error code, like following:

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:5f3b5f9d-001e-006e-704a-2897bf000000
Time:2017-09-08T02:30:35.6556584Z</Message></Error>
```

However, for getBlobMetadata/getBlobProperties, Node.js client library only gets HTTP error code 404, and doesn't know the exactly storage error code.

I don't think a client library should try to 'guess' the storage error code from HTTP error code, because there may updates or changes on the REST API definitions.

**Comment by jiacfan** [comment]
Hi, @electrachong 

Great to see your feedback again 👍

We can optimize the error message, and we cannot provide error code as BlobNotFound or ContainerNotFound, as it's not returned by service (mentioned by @XiaoningLiu ) -- [GetBlobProperties](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties)

Thanks,
Jiachen

**Comment by electrachong** [comment]
@XiaoningLiu @jiacfan Ah, yes, that makes sense, these head operations should not be able to get an xml body so cannot get the error code. Thanks for clarifying it to me!

I'll close the issue.
Best,
Electra
