### ISSUE TITLE
CERT_UNTRUSTED with blob storage in Germany Central

### ISSUE THREAD

**Issue by throrin19** [Azure/azure-storage-node#372]
Hi, I test to use the blob service with my storage account in germany central but, every time, I got the error 'CERT_UNTRUSTED` :

```
var azure = require('azure-storage');

var storage_name = 'heidelbergdata';
var storage_key    = 'xxxxxxxxxxxxx';
var storage_url      = 'https://heidelbergdata.blob.core.cloudapi.de/'

var blobService = azure.createBlobService(storage_name, storage_key, storage_url);

blobService.createBlockBlobFromLocalFile('files', 'file.txt', 'file.txt', function(error){
    // here, error returned the CERT_UNTRUSTED error
});
```

Have you a solution ?

- Node version : 0.12
- Azure-storage version : 2.6.0

**Comment by jiacfan** [comment]
Hi, @throrin19 

`CERT_UNTRUSTED` error typically happens when the request failed during HTTPs authentication.

From the `storage_url` and description, we see you are using an account in BlackForest. Have you tried to access the storage account from other approaches. For example, would you try to access a public blob directly from a popular browser, or access the azure portal with HTTPs protocal. Could you share the result? And check if there is certificate to be added into trusted root?

Thanks,
Jiachen

**Comment by throrin19** [comment]
After several tests, I think the problem is the version of node.JS. I test the code bellow with node 0.12 and node 8 and I have this result : 

- 0.12 : CERT_UNTRUSTED error
- 8.6 : the file upload correctly on storage

**Comment by jiacfan** [comment]
Hi, @throrin19 

As our testing, node.js version(e.g.: 4.x(>=4.8.3), 5.x, 6.x, 7.x, 8.x) would work fine. v0.10.x and v0.12.x which is announced as "End-of-Life" by [Node.js](https://github.com/nodejs/Release) is not officially supported by Azure storage node.js client library as well. Would you please upgrade your application to one of the node.js LTS version, or 5.x, 7.x?

Thanks,
Jiachen
