### ISSUE TITLE
Clarification on getBlobToStream vs. createReadStream 

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/azure-storage-node#389]
There are two very similar methods for creating a stream from a blob.  The [documentation](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-nodejs-how-to-use-blob-storage#download-blobs) and [api spec](http://azure.github.io/azure-storage-node/BlobService.html#createReadStream__anchor) don't cover the differences in any detail, just that:

getBlobToStream - writes the blob contents to a stream
createReadStream - provides a stream to read from the blob

First, are there any practical differences between these two methods?  Second, can we get the docs updated with the answer to that question?

**Comment by XiaoningLiu** [comment]
Yes, there are differences between them.

For `getBlobToStream`, the 'stream' here is a **WriteableStream**, such as a file write stream created by `fs.createWriteStream`. You can pass the file write stream as a parameter of this API  to directly download a blob to a local file.

For `createReadStream`, it returns a **ReadableStream**, you can use the returned read stream to pipe data chunks to other Writeable streams.

Streams in Node.js are very flexible, we can provide more flexibility by providing the both APIs.

**Comment by graham-sportsmgmt** [comment]
Thanks for the superb explanation.  It would be great if this could be added to the documentation to help others.

**Comment by alokrajiv** [comment]
Hi, understand this is a closed issue. 

Just a very generic question. 

I was searching quite a bit and was led astray by the fact that I was searching all the getters (in this case starting with `.get____`) and the doc never gave me the createReadStream.

Any convention or reasoning I'm forgetting that led to naming `createReadStream` instead of `getBlobToReadStream` or something along those lines, considering many other methods (LocalFile, Text, Stream, Properties, MetaData..) follow this prefix.

Sorry again to ping on 1yr+ old thread.

**Comment by XiaoningLiu** [comment]
@alokrajiv Thanks! These are the old naming conventions with long history, and not likely to change. We recommend the new released V10 series SDK in https://github.com/azure/azure-storage-js
