### ISSUE TITLE
Uncaught (in promise) TypeError: fs.stat is not a function

### ISSUE THREAD

**Issue by magiak** [Azure/azure-storage-node#410]
I tried to use createBlockBlobFromLocalFile but it throws an error "Uncaught (in promise) TypeError: fs.stat is not a function" in file blobservice.node.js on row 386.

**Comment by jiacfan** [comment]
Hi, @magiak 

Could you share how you call createBlockBlobFromLocalFile and your environment(Node.js version and platform)? As you know fs.stat is an API supported by Node.js File System since Node.js v0.0.2, the issue cannot be simply repo with latest Node.js and azure-storage-node lib from my side. Please provide more information.

Thanks,
Jiachen

**Comment by magiak** [comment]
Hi,
i am so sorry. It's my fault. I tried to use wrong function createBlockBlobFromLocalFile from web site. I had to use createBlockBlobFromBrowserFile.

**Comment by kalps1993** [comment]
Hello @magiak 

Please show me your code how to upload image from reactjs to azure container.
