### ISSUE TITLE
Storing and retrieving Int64 columns returns strings

### ISSUE THREAD

**Issue by geoffpatehutch** [Azure/azure-storage-node#411]
"use strict";

    var azure = require("azure-storage");

    var tableService = azure.createTableService("yourstorageaccountname", "yourstorageaccountkey");
    tableService.createTableIfNotExists("int64test", function (error) {
        if (error) {
            console.error(error);
            return;
        }

       var toInsert = {
            PartitionKey: azure.TableUtilities.entityGenerator.String("test1"),
            RowKey: azure.TableUtilities.entityGenerator.String("test1"),
            testdata64: azure.TableUtilities.entityGenerator.Int64(1),
            testdata32: azure.TableUtilities.entityGenerator.Int32(1)
        };

        tableService.insertEntity("int64test", toInsert, function (error) {
            if (error) {
                console.error(error);
                return;
            }

            tableService.retrieveEntity("int64test", "test1", "test1", function (error, result) {
                if (error) {
                    console.error(error);
                    return;
                }

                console.log(JSON.stringify(result));
                console.log(typeof result.testdata64._);
                console.log(result.testdata64._);
                console.log(typeof result.testdata32._);
                console.log(result.testdata32._);
            });
        });
    });

If you run the above code, the output shows the Int64 column is returned as a string
console.log(typeof result.testdata64._); => string

Compare with the Int32 column
console.log(typeof result.testdata64._); => number

**Comment by XiaoningLiu** [comment]
Table entity returned as OData Json format, according to the OData protocol, Int64 will represent as string.

http://www.odata.org/documentation/odata-version-2-0/json-format/

Primitive Type | JSON Serialization Format
-- | --
Edm.Binary | Base64 encoded value of an EDM.Binary value represented as a JSON string
Edm.Boolean | true \| false
Edm.Byte | Literal form of Edm.Byte as used in URIs formatted as a JSON string
Edm.DateTime | "/Date(<ticks>["+" \| "-" <offset>)/"<ticks> = number of milliseconds since midnight Jan 1, 1970<offset> = number of minutes to add or subtract
Edm.Decimal | Literal form of Edm.Decimal as used in URIs formatted as a JSON string
Edm.Double | Literal form of Edm.Double as used in URIs formatted as a JSON string
Edm.Guid | Literal form of Edm.Guid as used in URIs formatted as a JSON string
Edm.Int16 | A JSON number
Edm.Int32 | A JSON number
Edm.Int64 | A 64-bit integer formatted as a JSON string
Edm.SByte | Literal form of Edm.SByte as used in URIs formatted as a JSON string
Edm.Single | Literal form of Edm.Single as used in URIs formatted as a JSON string
Edm.String | Any JSON string
Edm.Time | Literal form of Edm.Time as used in URIs formatted as a JSON string
Edm.DateTimeOffset | Literal form of Edm.DateTimeOffset as used in URIs formatted as a JSON string

**Comment by geoffpatehutch** [comment]
Fair enough!
