### ISSUE TITLE
Speedsummary don't get updated when downloading file/blob under 32MB

### ISSUE THREAD

**Issue by suntobright** [Azure/azure-storage-node#443]
When downloading a file/blob smaller than 32MB, the property `completeSize` in `SpeedSummary` returned by `FileService.getFileToLocalFile()` / `BlobService.getBlobToLocalFile()` won't get updated, leaving the `SpeedSummary` useless.

**Comment by suntobright** [comment]
In the function `getFileToStream()` / `getBlobToStream()` of `fileservice.core.js` / `blobservice.core.js`, it calls `_getFileToRangeStream()` / `_getBlobToRangeStream()` if the size is bigger than threshold, otherwise it calls `_getFileToStream()` / `_getBlobToStream()`.

The control flow in `_getFileToStream()` / `_getBlobToStream()` did not update the `completeSize` in `SpeedSummary`.

I think it's a bug.

**Comment by jiacfan** [comment]
@suntobright 

Thanks for providing feedback!

What's the granularity of speed summary updating is wished? Per stream read or per service get request?

Currently  _getFileToRangeStream support per service request(to get one range) granularity. And _getFileToStream is by design not updating progress, as it only sends one service request to get entire blob/file.

Fine-grained speed updating is currently not supported, and for corase-grained speed updating(i.e. once update after 32MB- downloading finished) can be supported with some change. 

Welcome any contributions(PR)!

Thanks,
Jiachen

**Comment by suntobright** [comment]
I was hoping fine-grained updating, because the updating cost is very low.

If the original design is updating per request, the updating when downloading finished is necessary, in case that user may use `SpeedSummary`.

Even though, I think the updating is not identical in different code paths. For files bigger than 32MB, the updating grain is per 4MB. And for files smaller than 32MB, it's the whole file size. It's better to keep it identical.

**Comment by jiacfan** [comment]
@suntobright 

I see your wish to have fine grained progress updating. Downloading file smaller than 32MB is currently fulfilled with one request, updating progress with another grain(e.g. 4MB), is similar to fine grained progress. We will plan this feature request in the coming major release. 

For the per request updating, do you wish to try to contribute azure-storage-node code base with a PR? Welcome any discussion and contribution! 

Thanks,
Jiachen

**Comment by XiaoningLiu** [comment]
You can customize the 32MB default value therehold. 
```
blobService.singleBlobPutThresholdInBytes = customBlockSize;
```

**Comment by jiacfan** [comment]
@suntobright 

FYI, the per request updating, the change has been already involved in the latest branch.

Best Wishes,
Jiachen

**Comment by vinjiang** [comment]
Please let us know if you have further questions on this.
