### ISSUE TITLE
'close' is emitted before 'finish' for writable streams

### ISSUE THREAD

**Issue by mafintosh** [Azure/azure-storage-node#469]
When using `createWriteStreamToBlockBlob` it seems that the writable stream returned emits `close` before it emits `finish` when ending the stream.

```js
const ws = storage.createWriteStreamToBlockBlob(...)

ws.write(...)

ws.on('close', function () {
  console.log('onclose')
})

ws.on('finish', function () {
  console.log('onfinish')
})

ws.end()
```

Running the above I always get `onclose` before `onfinish`. This usually is interpretted as an error and make most stream libraries error (like [pump](https://github.com/mafintosh/pump), [end-of-stream](https://github.com/mafintosh/end-of-stream), the new [node core pipeline api](https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_stream_pipeline_streams_callback)).

**Comment by jiacfan** [comment]
@mafintosh 

Thanks for reporting candidate issues.

createWriteStreamToBlock should return [`ChunkStream`](https://github.com/Azure/azure-storage-node/blob/master/lib/common/streams/chunkstream.js)

And the normal logic is as following:
```
ChunkStream.prototype.finish = function () {
  this.emit('finish');

  this.destroy();
};

...

ChunkStream.prototype.destroy = function () {
  this.writable = this.readable = false;

  if (this._allocator && azureutil.objectIsFunction(this._allocator.destroy)) {
    this._allocator.destroy();
  }
  
  this.emit('close');
};
```

Where finish is emitted before close by design, and destroy is the only place emitting close event.

I'm interested to invite you into the investigation, and would you add some log in the code, repo the issue in your side, and check what cause the close event be emitted?

Thanks,
Jiachen

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance.
