### ISSUE TITLE
Can't write contentType using createBlockBlobFromStream

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/azure-storage-node#470]
My package.json has `"azure-storage": "^2.8.2"` which results in my current version being `2.9.0-preview`.

I am successfully writing a block blob using `createBlockBlobFromStream` but it's not accepting the contenttype parameter I am sending in.  The file name matches a document GUID from cosmosdb/documentdb.

This is the code I'm using to create the blob.  The metadata I'm passing in with the options is being stored successfully (see below).

```
module.exports.writeFileWithStream = function(fileSpec, stream, callback){

  let form = new multiparty.Form();

  form.on('part', function(part) {
    if (!part.filename) return;

    let size = part.byteCount;

    blobService.createBlockBlobFromStream(fileSpec.container, fileSpec.file, part, size, fileSpec.options, function(error) {

      if (error) {
        console.error(`ERROR in storage.writeFileWithStream\nFile Spec was: ${JSON.stringify(fileSpec)}\nError:\n${err}`);
        callback(error);
      }

      callback(null, 'File uploaded successfully');

    });
  });

  form.parse(stream);

}
```

Here is my fileSpec object from console.log:

```
{
   "container":"forms",
   "file": "75e146dc-cf30-d749-d0b4-b34ffb24628f",
   "options": {
     "contentSettings": {
       "contenttype": "image/jpeg"
     },
     "metadata": {
       "contenttype":"image/jpeg"
     }
   }
}
```

The file is being written correctly, but this is the result from `blobService.getBlobProperties(fileSpec.container, fileSpec.file` - the contentType has not changed from the default :

```
{
  container: 'forms',
  name: '75e146dc-cf30-d749-d0b4-b34ffb24628f',
  metadata: { contenttype: 'image/jpeg' },
  lastModified: 'Wed, 20 Jun 2018 16:36:23 GMT',
  etag: '"0x8D5D6CBF61C84E2"',
  blobType: 'BlockBlob',
  contentLength: '551900',
  serverEncrypted: 'true',
  requestId: 'c19f7481-501e-006a-7bbd-086cdd000000',
  contentSettings:
   { contentType: 'application/octet-stream',
     contentMD5: 'oJrfbG/5d7E8gMWB8pjWjA==' },
  lease: { status: 'unlocked', state: 'available' } 
}
```

**Comment by XiaoningLiu** [comment]
Hi @graham-sportsmgmt 

Please update `contenttype` to `contentType` in following configurations.
```
{
   "container":"forms",
   "file": "75e146dc-cf30-d749-d0b4-b34ffb24628f",
   "options": {
     "contentSettings": {
       "contenttype": "image/jpeg"
     },
     "metadata": {
       "contenttype":"image/jpeg"
     }
   }
}
```

**Comment by graham-sportsmgmt** [comment]
Thanks, this does fix it.  

I am sending this parameter through the http headers which automatically lowercases all keys, would it be possible to make this a case-insensitive property in a future release?

**Comment by XiaoningLiu** [comment]
@graham-sportsmgmt 

properties in metadata are case-insensitive, metadata "abc" and "ABC" are regarded as a same metadata.  because they are directly pared into header like `x-ms-metadataname`. HTTP header keys are case-insensitive. There is also no limit about how many key/value pairs added inside `metadata` properties.

But for properties in `contentSettings`, they are pre-defined. Only following are acceptable. Node.js property is case-sensitive. We retrieve the value of `options.contentSettings.contentType` and assign the value to header `Content-Type`.

contentType | string | <optional> | The MIME content type of the blob. The default type is application/octet-stream.
-- | -- | -- | --
contentEncoding | string | <optional> | The content encodings that have been applied to the blob.
contentLanguage | string | <optional> | The natural languages used by this resource.
cacheControl | string | <optional> | The Blob service stores this value but does not use or modify it.
contentDisposition | string | <optional> | The blob's content disposition.
contentMD5 | string | <optional>

**Comment by graham-sportsmgmt** [comment]
Thanks for the explanation.
