### ISSUE TITLE
ES Modules release

### ISSUE THREAD

**Issue by Avocher** [Azure/azure-storage-node#477]
Hi,
I don't know if this is the correct repository to request, but would it be possible to get an ES modules release for browsers? I ran into this issue https://github.com/Azure/azure-storage-node/issues/194 while trying to import azure-storage.blob.min.js.

**Comment by jiacfan** [comment]
Hi, @Avocher 

Currently the library doesn't exporting as ES module. Because of it’s bundled from Node.js code base which is based on CommonJS.

And we are developing a typescript library based on new architecture, and it could be compile into ES modules by TypeScript and Webpack. (The preview of this library could be in 2 months approximately)

Thanks,
Jiachen

**Comment by Avocher** [comment]
That is good news, thank you! Looking forward to the release. :100:
