### ISSUE TITLE
speedsummary.getCompletePercent inconsistent return type

### ISSUE THREAD

**Issue by Cellule** [Azure/azure-storage-node#488]
According to TypeScript typings [azureStorage.common.streams.speedsummary.SpeedSummary.getCompletePercent()](https://github.com/Azure/azure-storage-node/blob/master/typings/azure-storage/azure-storage.d.ts#L9079) should return a `number`.
However, in the [source](https://github.com/Azure/azure-storage-node/blob/master/lib/common/streams/speedsummary.js#L73) it actually returns a `string | number | undefined` according to the following code paths:
- `this.totalSize === 0` => number.
- `this.totalSize is truthy` => `string` because `number.toFixed(len)` returns a `string`
- `this.totalSize is falsy` => undefined 

I assume `this.totalSize` is always a `number`, but you could change the code to handle that case.

**Comment by jiacfan** [comment]
Hi, @Cellule 

Thanks for reporting issue! And welcome contribution.

Would you share more about how you find this issue? During developing in IDE, or some functional breaking you found during testings.

For the PR:
The definition is not supported by typescript@1.x. FYI, for new version typescript support, we have a typescript client library under developing with new architecture.

Would you help to update like following in order to be supported by typescript@1.x:
getElapsedSeconds(humanReadable?: boolean): string | number;
getCompletePercent( len?: number): string | number;
...

Best Regards,
Jiachen
