### ISSUE TITLE
Console Error - 404 Resource Not Found when using "IfNotExists" versions of the functions

### ISSUE THREAD

**Issue by jitendragarg** [Azure/azure-storage-node#503]
### Which service(blob, file, queue, table) does this issue concern?
I tried only with blob. Haven't tried others.

### Which version of the SDK was used?
2.10.101

### What problem was encountered?
If I use createContainer function, everything works fine. If I use createContainerIfNotExists, I get a 404 error logged in the console. Code still works fine, just the 404 error is bugging me out.

### Steps to reproduce the issue?
Try creating a container that doesn't exist using createContainerIfNotExists method. 

### Have you found a mitigation/solution?
Not yet.

**Comment by XiaoningLiu** [comment]
Hi @jitendragarg 

It's an expected behavior. createContainerIfNotExists will access to the container first in order to detect whether container exists. There will be a 404 if container not existing.

Unfortunately, the 404 is displayed by browsers, and cannot controlled by our library.

You can select "hide network" in the Chrome console to hide such network information.

![image](https://user-images.githubusercontent.com/6889160/44377906-61f18980-a531-11e8-868b-d0c15f195401.png)
