### ISSUE TITLE
JSDoc documentation is out of date

### ISSUE THREAD

**Issue by joaomoreno** [Azure/azure-storage-node#52]
The JSDoc generated documentation (http://dl.windowsazure.com/nodedocs/index.html) is out of date.

I couldn't understand why I wasn't able to insert entities into my tables. Eventually, I reached the Azure docs (http://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-table-storage/) and figured out there is a new syntax for table entities' properties: `key: {"_": "value"}`.

The JSDocs said nothing about this in the start page.

I suggest to either update or remove those docs.

**Comment by tracker1** [comment]
Not to mention woefully incomplete... there doesn't seem to be any documentation on azure.TableQuery, and for that matter that it's `.where` not  `.Where` etc... there's also the fact that you get an obscure error if you try to pass in a `.top` of over 1000, and no indication if the driver will actually return over a 1000 results for a query, if no top is specified... also, no apparent way to do paging of results in the client (skip/take).

While the product itself seems pretty cool good/thorough examples or documentation not to mention completeness of the client isn't there.  Also, that this issue is nearly a month old with no comments is a bit troubling.

**Comment by slepox** [comment]
@joaomoreno , the doc on (http://dl.windowsazure.com/nodedocs/index.html)  is for azure SDK not azure storage SDK, which is out of date too.
We uploaded the jsDoc on GitHub pages for this project on (http://azure.github.io/azure-storage-node), which is up to date as 0.4.4 now.

**Comment by tracker1** [comment]
@slepox Might want to update the links in the README.md for this project to point to said document...

**Comment by slepox** [comment]
@tracker1 the link is referenced in README section [Features](https://github.com/Azure/azure-storage-node#features)

**Comment by joaomoreno** [comment]
Excellent!

**Comment by tracker1** [comment]
@slepox thanks... may want to adjust the project's url (at the top), as it doesn't reference documentation related to node..

**Comment by slepox** [comment]
Thanks for checking, the original reference site was re-organized recently. The top link now is pointed to the reference doc now.
