### ISSUE TITLE
getBlobToLocalFile return result more than once

### ISSUE THREAD

**Issue by kiboliu** [Azure/azure-storage-node#558]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
2.6.0

### What's the Node.js/Browser version?
node 8

### What problem was encountered?
When using blob service as below to download blob file to local, sometimes the getBlobToLocalFile callback more than once. In the log, we can see firstly the function succeed with 'Blob succeed' and continue the following logic, but fail at the unzip process with cannot find the related file, which seems that downloading file failed before but return without error; then a log 'Blob error: {Error: Hash mismatch}' appears, which seems like the getBlobToLocalFile return result again and cause callback more than once.
```
const azure = require('azure-storage');
const blobSvc = azure.createBlobService(ACCOUNT, KEY);
function downloadFile(callback) {
    //get information
    ......
    blobSvc.getBlobToLocalFile(CONTAINER, BLOB_NAME, FILE_NAME, function(error, result, response) {
        if (error) {
            console.log('Blob error:', error);
            callback(error);
        } else {
            console.log('Blob succeed');
            callback(null);
        }
    });
}
// call downloadFile and unzip it if success
```
### Steps to reproduce the issue?
It happens rarely and I have no idea how to reproduce it.

### Have you found a mitigation/solution?
No idea. I see this function is parallel downloading file, shall I restrict it to only one thread? how can I do it?

**Comment by XiaoningLiu** [comment]
Hi @kiboliu I tried to reproduce the issue but unluckily failed. Data mismatch issue happens when server returned MD5 and SDK calculated MD5 doesn't match, it's likely the data is damaged during the transfer, in this case SDK will remove the downloaded file to avoid causing unknown behaviors. Double callback is strange here.

The download is not parallel. My recommendation is to retry the download when you got mismatch error or download file doesn't exist. Another recommendation is to try with our latest V10 storage JavaScript SDK, it has a cleaner implementation for upload/download. https://github.com/azure/azure-storage-js

I will look into the issue when there are more stable re-produce steps.

**Comment by kiboliu** [comment]
Thank you @XiaoningLiu for quick reply. I've tried retryPolicyFilter provided by the SDK as
```
const blobSvc = azure.createBlobService(ACCOUNT, KEY)
    .withFilter(new azure.ExponentialRetryPolicyFilter(RETRY_TIMES));
```
However this issue still appeared. I'm not sure if this retry policy will handle mismatch error, because from my log I did not see the download function had been retried. BTW, if this retry policy cannot handle this error, could you help me figure out how to customize it?

I'll also look at the latest V10 SDK to see if it can be easily adopted to our project.

**Comment by XiaoningLiu** [comment]
@kiboliu Yes, the retry policy built-in retry policy cannot handle MD5 mismatch issues. So you need retry in your logic code.

**Comment by XiaoningLiu** [comment]
Will close this issue, please re-open for more questions.
