### ISSUE TITLE
generateSharedAccessSignature returning date in wrong format

### ISSUE THREAD

**Issue by dagda1** [Azure/azure-storage-node#559]
### Which service(blob, file, queue, table) does this issue concern?

blob
### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?

8.11.1

### What problem was encountered?

`generateSharedAccessSignature` when used returning 403 make sure header is formatted correctly

### Steps to reproduce the issue?

I have this code:

```
var azure = require('azure-storage');

module.exports = function(context, req) {
  if (req.body.container) {
    // The following values can be used for permissions:
    // "a" (Add), "r" (Read), "w" (Write), "d" (Delete), "l" (List)
    // Concatenate multiple permissions, such as "rwa" = Read, Write, Add
    context.res = generateSasToken(
      context,
      req.body.container,
      req.body.blobName,
      req.body.permissions
    );
  } else {
    context.res = {
      status: 400,
      body: "Specify a value for 'container'"
    };
  }

  context.done(null, context);
};

function generateSasToken(context, container, blobName, permissions) {
  var connString = process.env.AzureWebJobsStorage;
  var blobService = azure.createBlobService(connString);

  // Create a SAS token that expires in an hour
  // Set start time to five minutes ago to avoid clock skew.
  var startDate = new Date();
  startDate.setMinutes(startDate.getMinutes() - 5);
  var expiryDate = new Date(startDate);
  expiryDate.setMinutes(startDate.getMinutes() + 60);

  permissions = permissions || azure.BlobUtilities.SharedAccessPermissions.READ + azure.BlobUtilities.SharedAccessPermissions.WRITE;

  var sharedAccessPolicy = {
    AccessPolicy: {
      Permissions: permissions,
      Start: startDate,
      Expiry: expiryDate
    }
  };

  var sasToken = blobService.generateSharedAccessSignature(
    container,
    blobName,
    sharedAccessPolicy
  );

  context.log(sasToken);

  return {
    token: sasToken,
    uri: blobService.getUrl(container, blobName, sasToken, true)
  };
}
```
BUt the date in the return token looks different if I go into the portal and create a token:

Portal token looks like this:

`?sv=2018-03-28&ss=b&srt=sco&sp=rwdlac&se=2019-01-30T23:19:06Z&st=2019-01-30T15:19:06Z&spr=https&sig=xxxxxxx`

response returned from `generateSharedAccessSignature`

```
st=2019-01-30T16%3A19%3A12Z&se=2019-01-30T17%3A19%3A12Z&sp=racw&sv=2018-03-28&sr=c&sig=AhtXpqFfhCnUjwcN5SBcA2hAZw0P35S32QeoTLeEWvQ%3D
```

The dates look different and the `sig` looks completely different also.

**Comment by XiaoningLiu** [comment]
Hi @dagda1 

Sas token differences you mentioned are expected.

Azure Storage provides 2 kinds of SAS tokens: Account Level SAS token and Service Level SAS token.

Account level SAS can provide access to cross services, like blob, queue, file. And service level SAS only provides access to specific service, like a blob.

Portal generated account level sas. And SDK could generate both. What `blobservice.generateSharedAccessSignature` does is to generate a service SAS.

I don't believe the 403 error is because SDK bug. 

Storage explorer is based on this SDK to generate both kinds of SAS tokens. You can try with storage explorer to see if it works.

For the permissions part, you must include permissions in the order that they appear in the table for the resource type

Permission | URI symbol | Allowed operations
-- | -- | --
Read | r | Read the content, properties, metadata and block list. Use the blob as the source of a copy operation.
Add | a | Add a block to an append blob.
Create | c | Write a new blob, snapshot a blob, or copy a blob to a new blob.
Write | w | Create or write content, properties, metadata, or block list. Snapshot or lease the blob. Resize the blob (page blob only). Use the blob as the destination of a copy operation.
Delete | d | Delete the blob. For version 2017-07-29 and later, the Delete permission also allows breaking a lease on a blob. See Lease Blob for more information.

See https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas

**Comment by dagda1** [comment]
i’m sorry that does not make a lot of sense to me.  all i want to do is returns a sas token to my website users can upload files.  my permissions are in the right order but i get the 403.  can you please help how to do this.  i don’t understand what i have to do and i can’t find any useful information. i’m coming from aws where everything just works to azure which is horrific.  lots of out of date docs and code and no real pointers how to do anything.  it is really depressing

**Comment by dagda1** [comment]
if i copy a token from the portal it works but the code i pasted gives 403.  i have no idea why this 403 is happening and what to do

**Comment by dagda1** [comment]
@XiaoningLiu how would I try it with storage explorer and what is storage explorer?

**Comment by dagda1** [comment]
I got this working.

Previously I was passing in the protocols in the `SharedAccessPolicy`.
```js
const permissions =
    permissions || azure.BlobUtilities.SharedAccessPermissions.READ + azure.BlobUtilities.SharedAccessPermissions.WRITE;

  const sharedAccessPolicy: azure.common.SharedAccessPolicy = {
    AccessPolicy: {
      Permissions: permissions,
      Start: startDate,
      Expiry: expiryDate,
      Protocols: SasConstants.Protocols.HTTPSONLY
    }
  };
```

I removed the protocols and it now works.

**Comment by dagda1** [comment]
Actually  I am mistaken,  it is still erroring.

Here is the url generated from the storage explorer:

```
https://mystorage.blob.core.windows.net/biocontainer?st=2019-02-02T21%3A54%3A23Z&se=2019-02-03T21%3A54%3A23Z&sp=rw&sv=2018-03-28&sr=c&sig=1hBEavg9BjqzuYojy550QetOv1l1egTbb8aAHzA7hQg%3D
```

And here is the url I am sending:
```
https://mystorage.blob.core.windows.net/biocontainer/table.gif?st=2019-02-02T22%3A05%3A45Z&se=2019-02-02T23%3A10%3A45Z&sp=rw&sv=2018-03-28&sr=c&sig=3h9jDCHzmS4JeEDDHvLcX6KlxZI%2F0yq9SykhCnxOGzk%3D
```

Here is the error response I get:

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:e18b2eb6-d01e-000b-7443-bbe343000000
Time:2019-02-02T22:06:36.0802354Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was rw
2019-02-02T22:01:35Z
2019-02-02T23:06:35Z
/blob/biomarkerstoragedev/biocontainer



2018-03-28




</AuthenticationErrorDetail></Error>
```

**Comment by dagda1** [comment]
@XiaoningLiu it looks like the encoding in the signature might be the problem.  Have you come across these problems?

**Comment by Prussia** [comment]
Hey, man. What is the resolution? I have a similar issue.

**Comment by katlimruiz** [comment]
Still also have this issue. container SAS generated thru azure portal works ok, but when do it thru the code, sometimes it works sometimes it doesn't.
